# Generated by Django 5.0 on 2024-01-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('total_pages', models.IntegerField()),
                ('author_name', models.CharField(max_length=100)),
            ],
        ),
    ]
